<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.g0oBK3t' shared service.

return $this->privates['.service_locator.g0oBK3t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.g0oBK3t.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.g0oBK3t": it references class "App\\Entity\\Article" but no such service exists.'],
    'slack' => ['privates', 'App\\Service\\SlackClient', 'getSlackClientService.php', true],
], [
    'article' => 'App\\Entity\\Article',
    'slack' => 'App\\Service\\SlackClient',
]);
