<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2oLUmmq' shared service.

return $this->privates['.service_locator.2oLUmmq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.2oLUmmq.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.2oLUmmq": it references class "App\\Entity\\Article" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'uploaderHelper' => ['privates', 'App\\Service\\UploaderHelper', 'getUploaderHelperService.php', true],
], [
    'article' => 'App\\Entity\\Article',
    'em' => '?',
    'uploaderHelper' => 'App\\Service\\UploaderHelper',
]);
