<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.u_DO8Ox' shared service.

return $this->privates['.service_locator.u_DO8Ox'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'reference' => ['privates', '.errored..service_locator.u_DO8Ox.App\\Entity\\ArticleReference', NULL, 'Cannot autowire service ".service_locator.u_DO8Ox": it references class "App\\Entity\\ArticleReference" but no such service exists.'],
    'uploaderHelper' => ['privates', 'App\\Service\\UploaderHelper', 'getUploaderHelperService.php', true],
], [
    'reference' => 'App\\Entity\\ArticleReference',
    'uploaderHelper' => 'App\\Service\\UploaderHelper',
]);
