<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ml31ViB' shared service.

return $this->privates['.service_locator.ml31ViB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'reference' => ['privates', '.errored..service_locator.ml31ViB.App\\Entity\\ArticleReference', NULL, 'Cannot autowire service ".service_locator.ml31ViB": it references class "App\\Entity\\ArticleReference" but no such service exists.'],
    'serializer' => ['services', 'serializer', 'getSerializerService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'reference' => 'App\\Entity\\ArticleReference',
    'serializer' => '?',
    'validator' => '?',
]);
