<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.m7kjZ_H' shared service.

return $this->privates['.service_locator.m7kjZ_H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'formAuthenticator' => ['privates', 'App\\Security\\LoginFormAuthenticator', 'getLoginFormAuthenticatorService.php', true],
    'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService.php', true],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
], [
    'formAuthenticator' => 'App\\Security\\LoginFormAuthenticator',
    'guardHandler' => '?',
    'passwordEncoder' => '?',
]);
