<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CDP_h5P' shared service.

return $this->privates['.service_locator.CDP_h5P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'repository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService.php', true],
], [
    'paginator' => '?',
    'repository' => 'App\\Repository\\CommentRepository',
]);
