<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xI.DK3Q' shared service.

return $this->privates['.service_locator.xI.DK3Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.xI.DK3Q.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.xI.DK3Q": it references class "App\\Entity\\Article" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
], [
    'article' => 'App\\Entity\\Article',
    'em' => '?',
    'logger' => '?',
]);
