<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\ApiTokenAuthenticator' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-guard/AuthenticatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-guard/AbstractGuardAuthenticator.php';
include_once \dirname(__DIR__, 4).'/src/Security/ApiTokenAuthenticator.php';

return $this->privates['App\\Security\\ApiTokenAuthenticator'] = new \App\Security\ApiTokenAuthenticator(($this->privates['App\\Repository\\ApiTokenRepository'] ?? $this->load('getApiTokenRepositoryService.php')));
