<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.App\Security\Voter\ArticleVoter' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
include_once \dirname(__DIR__, 4).'/src/Security/Voter/ArticleVoter.php';

return $this->privates['debug.security.voter.App\\Security\\Voter\\ArticleVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \App\Security\Voter\ArticleVoter(($this->privates['security.helper'] ?? $this->load('getSecurity_HelperService.php'))), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
