<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.FESfOvT.App\Entity\ArticleReference' shared service.

$this->throw('Cannot autowire service ".service_locator.FESfOvT": it references class "App\\Entity\\ArticleReference" but no such service exists.');
