<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_imagine.binary.loader.flysystem_loader' shared service.

include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/Loader/LoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/Loader/FlysystemLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mime/MimeTypeGuesserInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mime/MimeTypesInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mime/MimeTypes.php';

return $this->services['liip_imagine.binary.loader.flysystem_loader'] = new \Liip\ImagineBundle\Binary\Loader\FlysystemLoader(\Symfony\Component\Mime\MimeTypes::getDefault(), ($this->services['oneup_flysystem.uploads_filesystem_filesystem'] ?? $this->load('getOneupFlysystem_UploadsFilesystemFilesystemService.php')));
