<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\UploaderHelper' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Service/UploaderHelper.php';

return $this->privates['App\\Service\\UploaderHelper'] = new \App\Service\UploaderHelper(($this->services['oneup_flysystem.uploads_filesystem_filesystem'] ?? $this->load('getOneupFlysystem_UploadsFilesystemFilesystemService.php')), ($this->privates['assets.context'] ?? $this->getAssets_ContextService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), $this->getEnv('string:SITE_BASE_URL').'/uploads');
