<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjFHw4t\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjFHw4t/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRjFHw4t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRjFHw4t\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRjFHw4t\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RjFHw4t',
    'container.build_id' => 'c2949c3c',
    'container.build_time' => 1726987589,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjFHw4t');
