<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_modules_es_array-2eeec5.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-f501cc.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'article_show' => [
            'js' => [
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/article_show.js',
            ],
            'css' => [
                '/build/article_show.css',
            ],
        ],
        'admin_article_form' => [
            'js' => [
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_modules_es_array-2eeec5.js',
                '/build/vendors-node_modules_autocomplete_js_dist_autocomplete_jquery_js-node_modules_dropzone_dist_d-bc303f.js',
                '/build/admin_article_form.js',
            ],
            'css' => [
                '/build/admin_article_form.css',
            ],
        ],
        'account' => [
            'css' => [
                '/build/account.css',
            ],
        ],
        'login' => [
            'css' => [
                '/build/login.css',
            ],
        ],
    ],
],

]];
